-- Create client table
create table if not exists public.client (
    clientid bigint generated by default as identity primary key,
    name text not null,
    description text,
    contact_email text,
    status text default 'Active',
    created_at timestamp with time zone default now()
);

-- Enable Row Level Security (RLS)
alter table public.client enable row level security;

-- Create policy to allow all access for authenticated users (adjust as needed)
create policy "Allow all access for authenticated users" on public.client
    for all using (true) with check (true);

-- Add client_id column to project table if it doesn't exist
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'project' and column_name = 'clientid') then
        alter table public.project add column clientid bigint references public.client(clientid);
    end if;
end $$;
